const crypto = require("crypto"), SHA256 = message => crypto.createHash("sha256").update(message).digest("hex");
const EC = require("elliptic").ec, ec = new EC("secp256k1");
const MINT_PRIVATE_ADDRESS = "0700a1ad28a20e5b2a517c00242d3e25a88d84bf54dce9e1733e6096e6d6495e";
const MINT_KEY_PAIR = ec.keyFromPrivate(MINT_PRIVATE_ADDRESS, "hex");
const MINT_PUBLIC_ADDRESS = MINT_KEY_PAIR.getPublic("hex");

class Transaction { 
    constructor(from, to, amount, gas = 1, args = [], timestamp = Date.now().toString()) {
        // Sender's address
        this.from = from;
        // Recipient's address
        this.to = to;
        // Amount to be sent
        this.amount = amount;
        // Transaction's gas, default is 1
        this.gas = gas;
        // Additional arguments
        this.args = args;
        // Transaction creation timestamp
        this.timestamp = timestamp;
    } 
 
    sign(keyPair) { 
        if (keyPair.getPublic("hex") === this.from) {
            // The signature is generated by signing the hash which contains the sender's address, the recipient's address, amount, gas, args and timestamp.
            this.signature = keyPair.sign(SHA256(this.from + this.to + this.amount + this.gas + JSON.stringify(this.args) + this.timestamp), "base64").toDER("hex"); 
        } 
    } 
 
    static isValid(tx, state) {
        // A transaction is valid when the "from" and "to" addresses are not empty, the amount of 
        // money sent is not below 0, the gas is at least 1, the sender's balance is big enough
        // to create transactions, the timestamp is less than the moment we check, the signature
        // matches with the public key, the timestamp does not exist in the used timestamps list.

        return ( 
            tx.from && 
            tx.to && 
            tx.amount >= 0 && 
            (((state[tx.from] ? state[tx.from].balance : 0) >= tx.amount + tx.gas && tx.gas >= 1) || tx.from === MINT_PUBLIC_ADDRESS) && 
            ec.keyFromPublic(tx.from, "hex").verify(SHA256(tx.from + tx.to + tx.amount + tx.gas + JSON.stringify(tx.args) + tx.timestamp), tx.signature) &&
            state[tx.from] ? !state[tx.from].timestamps.includes(tx.timestamp) : true
        )
    }
}

module.exports = Transaction;
